version: "2"

networks:
  app-tier:
    driver: bridge

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - 'mongodb_data:/data/db'
    #environment:
    #  MONGO_INITDB_DATABASE: test
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: 1q2w3e
    ports: 
      - 27017:27017
    networks: 
      - app-tier

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    #environment:
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: 1q2w3e
    networks: 
      - app-tier

  node:
    image: "node-qs:latest"
    user: "root"
    working_dir: /app
    environment:
      - NODE_ENV=develop
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
      - "80:80"
    stdin_open: true
    tty: true
    links:
      - "mongo"
      - "mongo-express"
    #entrypoint: "nodemon start"
    networks: 
      - app-tier

volumes:
  mongodb_data:
    driver: local
